Repository ME-ICA/aroma, pull requests merged in 2020-11, with the labels that each got.

#18 Replace print statements with logger
  aroma/_version.py
  aroma/aroma.py
  aroma/features.py
  aroma/plotting.py
  aroma/utils.py
Labels: enhancement

#20 [REF] Use pandas for feature arrays
  aroma/aroma.py
  aroma/cli/classification_plot.py
  aroma/plotting.py
  aroma/utils.py
  setup.cfg
Labels: refactoring

#26 Fix cli bug
  aroma/cli/aroma.py
  setup.cfg
  setup.py
Labels: bugfix

#33 Fix utils.py classification function errors
  aroma/tests/conftest.py
  aroma/tests/data/classification_overview.txt
  aroma/tests/data/classified_motion_ICs.txt
  aroma/tests/data/feature_scores.txt
  aroma/tests/test_integration.py
  aroma/utils.py
Labels: Bug Fix, High Priority

#36 Add Code of Conduct and Contribution Guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: Community, Documentation
